config/routes.rb
Rails.application.routes.draw do
  resources :bank_subsidiaries
  resources :banks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'banks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
	has_many :bank_subsidiaries, dependent: :destroy
	accepts_nested_attributes_for :bank_subsidiaries, 
		reject_if: proc { |attr| attr['address'].blank? },
		allow_destroy: true
	validates :name, presence: true

	def to_s
		name
	end
end

app/models/bank_subsidiary.rb
class BankSubsidiary < ApplicationRecord
  	belongs_to :bank
  	validates :address, presence: true

  	def to_s
  		address
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bank_subsidiaries_controller.rb
class BankSubsidiariesController < ApplicationController
  before_action :set_bank_subsidiary, only: [:show, :edit, :update, :destroy]

  # GET /bank_subsidiaries
  # GET /bank_subsidiaries.json
  def index
    @bank_subsidiaries = BankSubsidiary.all
  end

  # GET /bank_subsidiaries/1
  # GET /bank_subsidiaries/1.json
  def show
  end

  # GET /bank_subsidiaries/new
  def new
    @bank_subsidiary = BankSubsidiary.new
  end

  # GET /bank_subsidiaries/1/edit
  def edit
  end

  # POST /bank_subsidiaries
  # POST /bank_subsidiaries.json
  def create
    @bank_subsidiary = BankSubsidiary.new(bank_subsidiary_params)

    respond_to do |format|
      if @bank_subsidiary.save
        format.html { redirect_to @bank_subsidiary, notice: 'Bank subsidiary was successfully created.' }
        format.json { render :show, status: :created, location: @bank_subsidiary }
      else
        format.html { render :new }
        format.json { render json: @bank_subsidiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_subsidiaries/1
  # PATCH/PUT /bank_subsidiaries/1.json
  def update
    respond_to do |format|
      if @bank_subsidiary.update(bank_subsidiary_params)
        format.html { redirect_to @bank_subsidiary, notice: 'Bank subsidiary was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_subsidiary }
      else
        format.html { render :edit }
        format.json { render json: @bank_subsidiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_subsidiaries/1
  # DELETE /bank_subsidiaries/1.json
  def destroy
    @bank_subsidiary.destroy
    respond_to do |format|
      format.html { redirect_to bank_subsidiaries_url, notice: 'Bank subsidiary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_subsidiary
      @bank_subsidiary = BankSubsidiary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_subsidiary_params
      params.require(:bank_subsidiary).permit(:address, :bank_id)
    end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
    @bank.bank_subsidiaries.build
  end

  # GET /banks/1/edit
  def edit
    @bank.bank_subsidiaries.build
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name, bank_subsidiaries_attributes: [:id, :address, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_subsidiaries_helper.rb
module BankSubsidiariesHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/bank_subsidiaries/_form.html.erb
<%= form_with(model: bank_subsidiary, local: true) do |form| %>
  <% if bank_subsidiary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank_subsidiary.errors.count, "error") %> prohibited this bank_subsidiary from being saved:</h2>

      <ul>
      <% bank_subsidiary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :bank_subsidiary_address %>
  </div>

  <div class="field">
    <%= form.label :bank_id %>
    <%= form.text_field :bank_id, id: :bank_subsidiary_bank_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bank_subsidiaries/edit.html.erb
<h1>Editing Bank Subsidiary</h1>

<%= render 'form', bank_subsidiary: @bank_subsidiary %>

<%= link_to 'Show', @bank_subsidiary %> |
<%= link_to 'Back', bank_subsidiaries_path %>

app/views/bank_subsidiaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bank Subsidiaries</h1>

<table class="table">
  <thead>
    <tr>
      <th>Address</th>
      <th>Bank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_subsidiaries.each do |bank_subsidiary| %>
      <tr>
        <td><%= bank_subsidiary.address %></td>
        <td><%= bank_subsidiary.bank %></td>
        <td><%= link_to 'Show', bank_subsidiary %></td>
        <td><%= link_to 'Edit', edit_bank_subsidiary_path(bank_subsidiary) %></td>
        <td><%= link_to 'Destroy', bank_subsidiary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank Subsidiary', new_bank_subsidiary_path %>

app/views/bank_subsidiaries/new.html.erb
<h1>New Bank Subsidiary</h1>

<%= render 'form', bank_subsidiary: @bank_subsidiary %>

<%= link_to 'Back', bank_subsidiaries_path %>

app/views/bank_subsidiaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @bank_subsidiary.address %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @bank_subsidiary.bank %>
</p>

<%= link_to 'Edit', edit_bank_subsidiary_path(@bank_subsidiary) %> |
<%= link_to 'Back', bank_subsidiaries_path %>

app/views/banks/_form.html.erb
<%= form_with(model: bank, local: true) do |form| %>
  <% if bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <h2>Sucursales</h2>
  <%= form.fields_for :bank_subsidiaries do |subsidiary| %>
    <div class="bank_subsidiaries_fields">
      <div class="fields">
        <%= subsidiary.label :address, "Direccion" %>
        <%= subsidiary.text_field :address %>
        <%= subsidiary.check_box :_destroy %>
        <%= subsidiary.label :_destroy, "Borrar" %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing Bank</h1>

<%= render 'form', bank: @bank %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Banks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.name %></td>
        <td><%= link_to 'Show', bank %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>New Bank</h1>

<%= render 'form', bank: @bank %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bank.name %>
</p>

<h2>Sucursales</h2>
<% if @bank.bank_subsidiaries.any? %>
	<ul>
	<% @bank.bank_subsidiaries.each do |subsidiary| %>
		<li><%= link_to subsidiary, subsidiary  %></li>
	<% end %>
	</ul>
<% else%>
	<p>No hay sucursales</p>
<% end %>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba08</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">Mi Sitio</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li class="active"><a href="../banks">Inicio</a></li>
	      <li class="dropdown">
	        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Bancos
	        <span class="caret"></span></a>
	        <ul class="dropdown-menu">
	          <li><a href="./banks/1">BCP</a></li>
	          <li><a href="./banks/2">BBVA</a></li>
	        </ul>
	      </li>
	      <li><a href="../bank_subsidiaries">Sucursales</a></li>
	    </ul>
	  </div>
	</nav>
    <%= yield %>
  </body>
</html>